version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: maven
    directory: integration-test/spring-boot/
    schedule:
      interval: weekly
