content:
  # If a page originates from the local file system, then the environment variable CI
  # must be set for the default UI to apply edit_url.
  # https://docs.antora.org/antora/latest/playbook/content-edit-url/
  edit_url: 'https://github.com/pukkaone/grapid/blob/main/{path}'
  sources:
  - branches: HEAD
    start_path: site/documentation
    url: ..
    version: '${project.version}'
  - branches: HEAD
    start_path: site/home
    url: ..
    version: ~

output:
  dir: build/site

site:
  keys:
    google_analytics: UA-7747045-3
  start_page: home::index.adoc
  title: Grapid
  url: https://pukkaone.github.io/grapid

ui:
  bundle:
    snapshot: true
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
  supplemental_files: supplemental-ui

urls:
  html_extension_style: indexify
  latest_version_segment: current
