name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow

    - uses: actions/setup-java@v3.8.0
      with:
        cache: gradle
        distribution: temurin
        java-version: '17'

    - run: gradle publishToMavenLocal check
